# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2022-02-08 03:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.datetime_safe
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='id',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='id',
        ),
        migrations.AddField(
            model_name='slot',
            name='slot_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theatre',
            name='theatre_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
