# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2022-02-08 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_auto_20220208_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot_date',
            field=models.DateField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
