# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2022-02-08 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_auto_20220208_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='slot_date',
            field=models.DateField(max_length=20),
        ),
    ]
